[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "php artisan migrate --force && php artisan db:seed --class=RolesAndPermissionsSeeder --force"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10