<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionDistrictSeeder extends Seeder
{
    // official 16 regions and 261 MMDAs, sourced from ghanadistricts.com (2025–2029 summary)
    private const REGIONS = [
        'Ashanti' => [
            'Adansi North District',
            'Adansi South District',
            'Afigya Kwabre South Municipal',
            'Ahafo Ano North Municipal',
            'Ahafo Ano South West District',
            'Amansie Central District',
            'Amansie West District',
            'Asante Akim Central Municipal',
            'Asante Akim North Municipal',
            'Asante Akim South Municipal',
            'Asokore Mampong Municipal',
            'Atwima Kwanwoma Municipal',
            'Atwima Mponua District',
            'Atwima Nwabiagya South Municipal',
            'Bekwai Municipal',
            'Bosome Freho District',
            'Bosomtwe District',
            'Ejisu Municipal',
            'Ejura Sekyedumase Municipal',
            'Kumasi Metropolitan',
            'Kwabre East Municipal',
            'Mampong Municipal',
            'Obuasi Municipal',
            'Offinso Municipal',
            'Offinso North Municipal',
            'Sekyere Afram Plains District',
            'Sekyere Central District',
            'Sekyere East District',
            'Sekyere Kumawu District',
            'Sekyere South Municipal',
            'Oforikrom Municipal',
            'Kwadaso Municipal',
            'Old Tafo Municipal',
            'Asokwa Municipal',
            'Suame Municipal',
            'Juaben Municipal',
            'Ahafo Ano South East District',
            'Amansie South District',
            'Atwima Nwabiagya North Municipal',
            'Akrofuom District',
            'Adansi Asokwa District',
            'Obuasi East Municipal',
            'Afigya Kwabre North Municipal',
        ],
        'Bono' => [
            'Banda District',
            'Berekum East Municipal',
            'Dormaa Central Municipal',
            'Dormaa East District',
            'Dormaa West District',
            'Jaman North District',
            'Jaman South Municipal',
            'Sunyani Metropolitan',
            'Sunyani West Municipal',
            'Tain District',
            'Wenchi Municipal',
            'Berekum West District',
        ],
        'Bono East' => [
            'Atebubu Amantin Municipal',
            'Kintampo North Municipal',
            'Kintampo South District',
            'Nkoranza South Municipal',
            'Nkoranza North District',
            'Pru East Municipal',
            'Sene East District',
            'Sene West District',
            'Techiman Metropolitan',
            'Techiman North Municipal',
            'Pru West District',
        ],
        'Ahafo' => [
            'Asunafo North Municipal',
            'Asunafo South District',
            'Asutifi North District',
            'Asutifi South District',
            'Tano North Municipal',
            'Tano South Municipal',
        ],
        'Central' => [
            'Abura Asebu Kwamankese District',
            'Agona East District',
            'Agona West Municipal',
            'Ajumako Enyan Essiam District',
            'Asikuma Odoben Brankwa District',
            'Assin Foso Municipal',
            'Assin South District',
            'Awutu Senya East Municipal',
            'Awutu Senya West District',
            'Cape Coast Metropolitan',
            'Effutu Municipal',
            'Ekumfi District',
            'Gomoa Central District',
            'Gomoa West District',
            'Komenda Edina Eguafo Abirem Municipal',
            'Mfantseman Municipal',
            'Twifo Atti Morkwa District',
            'Twifo Heman Lower Denkyira District',
            'Upper Denkyira East Municipal',
            'Upper Denkyira West District',
            'Assin North District',
            'Gomoa East Municipal',
        ],
        'Eastern' => [
            'Akuapem North Municipal',
            'Akuapim South Municipal',
            'Akyemansa District',
            'Asuogyaman District',
            'Atiwa West District',
            'Ayensuano District',
            'Birim Central Municipal',
            'Birim North Municipal',
            'Birim South District',
            'Denkyembour District',
            'Abuakwa South Municipal',
            'Fanteakwa North District',
            'Kwaebibirem Municipal',
            'Kwahu Afram Plains North District',
            'Kwahu Afram Plains South District',
            'Kwahu East District',
            'Kwahu South Municipal',
            'Kwahu West Municipal',
            'Lower Manya Krobo Municipal',
            'New Juaben South Metropolitan',
            'Nsawam Adoagyiri Municipal',
            'Suhum Municipal',
            'Upper Manya Krobo District',
            'Upper West Akim District',
            'West Akim Municipal',
            'Yilo Krobo Municipal',
            'Okere District',
            'Atiwa East District',
            'Fanteakwa South District',
            'Asene Manso Akroso District',
            'Abuakwa North Municipal',
            'New Juaben North Municipal',
            'Achiase District',
        ],
        'Greater Accra' => [
            'Accra Metropolitan',
            'Ada West District',
            'Ada East District',
            'Adentan Municipal',
            'Ashaiman Municipal',
            'Ga Central Municipal',
            'Ga South Municipal',
            'Ga East Municipal',
            'Ga West Municipal',
            'La Dade Kotopon Municipal',
            'Ledzokuku Municipal',
            'La Nkwantanang Madina Municipal',
            'Ningo Prampram Municipal',
            'Shai Osudoku District',
            'Tema Metropolitan',
            'Kpone Katamanso Metropolitan',
            'Okaikwei North Municipal',
            'Ablekuma North Municipal',
            'Ablekuma West Municipal',
            'Ayawaso East Municipal',
            'Ayawaso North Municipal',
            'Ayawaso West Municipal',
            'Ga North Municipal',
            'Weija Gbawe Municipal',
            'Tema West Municipal',
            'Krowor Municipal',
            'Korle Klottey Municipal',
            'Ablekuma Central Municipal',
            'Ayawaso Central Municipal',
        ],
        'Northern' => [
            'Gushegu Municipal',
            'Karaga Municipal',
            'Kpandai District',
            'Kumbungu District',
            'Mion District',
            'Nanumba North Municipal',
            'Nanumba South District',
            'Saboba District',
            'Sagnarigu Municipal',
            'Savelugu Municipal',
            'Tamale Metropolitan',
            'Tatale/Sanguli District',
            'Tolon District',
            'Yendi Municipal',
            'Zabzugu District',
            'Nanton District',
        ],
        'North East' => [
            'Bunkpurugu Nakpanduri District',
            'Chereponi District',
            'East Mamprusi Municipal',
            'Mamprugu Moagduri District',
            'West Mamprusi Municipal',
            'Yunyoo-Nasuan District',
        ],
        'Savannah' => [
            'Bole Municipal',
            'Central Gonja District',
            'East Gonja Municipal',
            'North Gonja District',
            'Sawla-Tuna-Kalba District',
            'West Gonja Municipal',
            'North East Gonja District',
        ],
        'Upper East' => [
            'Bawku Municipal',
            'Bawku West District',
            'Binduri District',
            'Bolgatanga Municipal',
            'Bongo District',
            'Builsa North Municipal',
            'Builsa South District',
            'Garu District',
            'Kassena Nankana Municipal',
            'Kassena Nankana West District',
            'Nabdam District',
            'Pusiga District',
            'Talensi District',
            'Bolgatanga East District',
            'Tempane District',
        ],
        'Upper West' => [
            'Daffiama Bussie Issa District',
            'Jirapa Municipal',
            'Lambussie Karni District',
            'Lawra Municipal',
            'Nadowli Kaleo District',
            'Nandom Municipal',
            'Sissala East Municipal',
            'Sissala West District',
            'Wa East District',
            'Wa Metropolitan',
            'Wa West District',
        ],
        'Volta' => [
            'Adaklu District',
            'Afadzato South District',
            'Agotime Ziope District',
            'Akatsi North District',
            'Akatsi South Municipal',
            'Central Tongu District',
            'Ho Metropolitan',
            'Ho West District',
            'Hohoe Municipal',
            'Keta Municipal',
            'Ketu North Municipal',
            'Ketu South Municipal',
            'Kpando Municipal',
            'North Dayi District',
            'North Tongu District',
            'South Dayi District',
            'South Tongu Municipal',
            'Anloga Municipal',
        ],
        'Oti' => [
            'Biakoye District',
            'Jasikan Municipal',
            'Kadjebi District',
            'Krachi East Municipal',
            'Krachi Nchumuru District',
            'Krachi West Municipal',
            'Nkwanta North District',
            'Nkwanta South Municipal',
            'Guan District',
        ],
        'Western' => [
            'Ahanta West Municipal',
            'Amenfi Central District',
            'Wassa Amenfi East Municipal',
            'Wassa Amenfi West Municipal',
            'Ellembelle District',
            'Jomoro Municipal',
            'Mpohor District',
            'Nzema East Municipal',
            'Prestea-Huni Valley Municipal',
            'Sekondi Takoradi Metropolitan',
            'Shama Municipal',
            'Tarkwa-Nsuaem Municipal',
            'Wassa East District',
            'Effia Kwesimintsim Municipal',
        ],
        'Western North' => [
            'Aowin Municipal',
            'Bia East District',
            'Bia West District',
            'Bibiani-Anhwiaso Bekwai Municipal',
            'Bodi District',
            'Juaboso District',
            'Sefwi Akontombra District',
            'Sefwi Wiawso Municipal',
            'Suaman District',
        ],
    ];

    public function run(): void
    {
        foreach (self::REGIONS as $regionName => $districts) {
            $region = Region::firstOrCreate(['name' => $regionName]);

            foreach ($districts as $districtName) {
                District::firstOrCreate([
                    'name' => $districtName,
                    'region_id' => $region->id,
                ]);
            }
        }
    }
}
