name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGING }}
    steps:
      - uses: actions/checkout@v4
      - run: railway up --service=backend --detach

  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: railway up --service=backend --detach
